php:
  preset: laravel
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
      - server.php
js:
  preset: vue
  name: "*.vue"
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    not-name:
      - webpack.mix.js
css: true
